### ISSUE TITLE
Uncaught Error: Evaluation failed: TypeError: Cannot read property 'innerText' of null

### ISSUE THREAD

**Issue by alexporter7** [HaiDang666/extract-sptf-playlist#6]
Used this for a single playlist and it worked great however I'm unable to get another one to convert and I'm not particularly sure why. I tried running through a list of playlists

```javascript
for( i = 0; i < youtubePlaylistData.playlists.length; i++ ) {
    getYoutubePlaylist(youtubePlaylistData.playlists[i].url, {
        filePath: "./output/" + youtubePlaylistData.playlists[i].name + ".json",
        displayProcess: true,
        headless: true,
        trackFormatterFn: defaultYoutubeTrackFormatter,
    });  
    console.log("[{0}/{1}] - Processed [{2}] [{3}]"
        .format(
            i + 1, 
            youtubePlaylistData.playlists.length, 
            youtubePlaylistData.playlists[i].name,
            youtubePlaylistData.playlists[i].url));
}
```
And had one of the playlists successfully convert but none of the others out of 3. After debugging and trying again with just a single playlist as shown in the example

```javascript
getYoutubePlaylist(url, {
    filePath: './output/test.json', 
    displayProcess: true, 
    headless: true, 
    trackFormatterFn: defaultYoutubeTrackFormatter,});
```
I'm still receiving the same error. Have I hit some kind of limiter within youtube's API and they're blocking the requests?

**Comment by haidang666** [comment]
I think it's not about API limiting cos this uses headless chrome, can you set `headless: false` to observe the process? I gonna add more checks for `null` variable.

**Comment by alexporter7** [comment]
Thanks! I honestly wasn't even aware of what `headless` was doing but that seemed to do the trick, I think you're right.
